routes/web.php
<?php



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'PagesController@index');
Route::get('/visiting', 'PagesController@visiting');
Route::get('/credits', 'PagesController@credits');

//User specific stuff
Route::get('login', 'LoginController@showLoginForm');
Route::post('login', 'LoginController@login');
Route::get('/forums/sso', 'LoginController@forumsSso');
Route::get('logout', 'LoginController@logout');
Route::get('dashboard', 'UsersController@index');
Route::get('dashboard/feedback/{feedback}', 'FeedbackController@show');
Route::get('dashboard/changepass', 'UsersController@changePass');
Route::post('dashboard/changepass', 'UsersController@updatePass');
Route::get('dashboard/profile/edit', 'UsersController@editProfile');
Route::patch('dashboard/profile', 'UsersController@updateProfile');
Route::get('dashboard/avail', 'AvailController@index');
Route::post('dashboard/avail', 'AvailController@store');
Route::get('dashboard/avail/create', 'AvailController@create');
Route::get('dashboard/avail/delete/{avail}', 'AvailController@delete');
Route::get('forgotpass', 'LoginController@forgotpass');
Route::post('forgotpass', 'LoginController@generateResetToken');
Route::get('forgotpass/{token}', 'LoginController@sendNewPassword');

//Controllers
Route::get('controllers', 'ControllersController@index');
Route::get('controllers/staff', 'ControllersController@staff');
Route::get('controllers/ins', 'ControllersController@ins');
Route::get('controllers/{user}', 'ControllersController@show');
Route::get('admin/controllers/create', 'AdminControllersController@create');
Route::get('admin/controllers/search', 'AdminControllersController@search');
Route::get('admin/controllers/search/{data}', 'AdminControllersController@searchResults');
Route::get('ins/controllers/search', 'InsControllersController@search');
Route::get('ins/controllers/search/{data}', 'InsControllersController@searchResults');
Route::post('ins/controllers/search/', 'InsControllersController@searchPost');
Route::get('ins/controllers/edit/{user}', 'InsControllersController@edit');
Route::post('ins/controllers/edit', 'InsControllersController@update');
Route::post('admin/controllers/delete/', 'AdminControllersController@delete');
Route::get('admin/controllers/edit/{cid}', 'AdminControllersController@edit');
Route::post('admin/controllers/edit/', 'AdminControllersController@update');
Route::post('admin/controllers', 'AdminControllersController@store');
Route::get('admin/controllers/restore/{cid}', 'AdminControllersController@verifyRestore');
Route::post('admin/controllers/restore/{cid}', 'AdminControllersController@restore');
Route::post('admin/controllers/search/', 'AdminControllersController@searchPost');
Route::get('admin/controllers/email/', 'AdminControllersController@massEmail');
Route::post('admin/controllers/email/', 'AdminControllersController@sendMassEmail');
Route::get('admin/controllers/activity', 'AdminControllersController@getActivity');
Route::get('admin/controllers/activity/{user}', 'AdminControllersController@getControllerActivity');
Route::get('emaillistputo', 'ControllersController@emailList');

//Events
Route::get('events', 'EventsController@index');
Route::get('admin/events', 'AdminEventsController@index');
Route::get('admin/events/create', 'AdminEventsController@create');
Route::post('admin/events', 'AdminEventsController@store');
Route::get('admin/events/edit/{id}', 'AdminEventsController@edit');
Route::post('admin/events/edit/{id}', 'AdminEventsController@update');
Route::post('admin/events/edit/file/{id}', 'AdminEventsController@replaceFile');
Route::post('admin/events/delete', 'AdminEventsController@delete');

//News
Route::get('/news', 'NewsController@index');
Route::get('/news/{news}', 'NewsController@show');
Route::get('/admin/news', 'AdminNewsController@index');
Route::get('/admin/news/create', 'AdminNewsController@create');
Route::post('admin/news', 'AdminNewsController@store');
Route::post('admin/news/delete/', 'AdminNewsController@delete');
Route::get('admin/news/edit/{id}', 'AdminNewsController@edit');
Route::post('admin/news/edit/{id}', 'AdminNewsController@update');

//INS
Route::get('/ins', 'InstructorController@index');

//Avail
Route::get('dashboard/avail/take/{id}', 'AvailController@take');
Route::post('dashboard/avail/take/{id}', 'AvailController@convertToSession');
Route::get('/ins/avail', 'InsAvailController@index');
Route::get('/ins/avail/{date}', 'InsAvailController@show');
Route::get('/ins/avail/take/{avail}', 'InsAvailController@take');
Route::post('/ins/avail/take/{id}', 'InsAvailController@store2');
Route::post('/ins/avail', 'InsAvailController@store');
Route::get('/ins/avail/create', 'InsAvailController@create');
Route::get('/ins/avail/delete/{id}', 'InsAvailController@delete');

//Training
Route::get('/dashboard/training', 'TrainingController@index');
Route::get('/dashboard/training/{id}', 'TrainingController@show');
Route::get('ins/training', 'InsTrainingController@index');
Route::get('ins/training/last20', 'InsTrainingController@last20');
Route::get('ins/training/{id}', 'InsTrainingController@details');
Route::post('ins/training/delete/', 'InsTrainingController@delete');
Route::post('ins/training/{id}', 'InsTrainingController@update');
Route::post('ins/training/finalize/{id}', 'InsTrainingController@finalize');
Route::get('ins/training/merge/{id1}/{id2}', 'InsTrainingController@merge');
Route::get('ins/controllers/training/{user}', 'InsTrainingController@viewSessions');

//Files
Route::get('files', 'FilesController@index');
Route::get('files/{id}', 'FilesController@get');
Route::get('admin/category', 'AdminCategoriesController@index');
Route::post('/admin/category', 'AdminCategoriesController@create');
Route::post('/admin/category/delete/', 'AdminCategoriesController@delete');
Route::get('admin/files', 'AdminFilesController@index');
Route::get('admin/files/create', 'AdminFilesController@create');
Route::post('admin/files', 'AdminFilesController@store');
Route::post('/admin/files/delete/', 'AdminFilesController@delete');
Route::get('admin/files/edit/{id}', 'AdminFilesController@edit');
Route::post('admin/files/edit/{id}', 'AdminFilesController@update');
Route::post('admin/files/edit/file/{id}', 'AdminFilesController@replaceFile');

//Documents
Route::get('/documents', 'DocumentController@index');
Route::get('/documents/{document}', 'DocumentController@show');
Route::get('/admin/documents', 'AdminDocumentController@index');
Route::post('/admin/documents', 'AdminDocumentController@store');
Route::post('/admin/documents/delete', 'AdminDocumentController@delete');
Route::get('/admin/documents/edit/{document}', 'AdminDocumentController@edit');
Route::post('/admin/documents/edit/{document}', 'AdminDocumentController@update');

//Feedback
Route::get('feedback', 'FeedbackController@index');
Route::post('feedback', 'FeedbackController@store');
Route::get('admin/feedback', 'AdminFeedbackController@index');
Route::post('admin/feedback/delete/', 'AdminFeedbackController@delete');
Route::get('admin/feedback/approve/{feedback}', 'AdminFeedbackController@approve');
Route::get('admin/feedback/{user}', 'AdminFeedbackController@show');

//Admin
Route::get('/admin', 'AdminController@index');

//Special AJAX stuff
Route::post('/admin/fetchcontroller/{cid}', 'AjaxController@fetchController');
Route::post('/admin/fetchoi/{oi}', 'AjaxController@fetchOi');
Route::post('/admin/category/sort', 'AjaxController@updateSort');
Route::post('/admin/file/sort', 'AjaxController@fileSort');
Route::post('/admin/document/sort', 'AjaxController@documentSort');


Route::get('/test', 'CronController@getDataFile');
Route::get('/test2', 'CronController@updatePilotsOnline');


// Route::get('/map', function() {
//     $pilots = \App\PilotsOnline::all();
//     return view('modules.map')->with(compact('pilots'));
// });

app/Document.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
	protected $dates = [
		'created_at',
		'updated_at',
	];
	protected $fillable = [
		'name',
		'description',
		'content',
		'last_update_user',
		'category',
		'uri_slug',
		'sort'
	];

	public function category() {

		return $this->belongsTo('App\FileCategory', 'category');
		
	}

	public function user() {

		return $this->belongsTo('App\User', 'user_cid')->withTrashed();
		
	}
}

app/Http/Controllers/DocumentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DocumentController extends Controller
{
	public function index() {
    
		$category = \App\FileCategory::where('access', 1)->withCount('document')->get();

		return view('documents.index', compact('category'));
		
	}

	public function show($document) {
		$doc = \App\Document::where('uri_slug', $document)->first();

		$pd = new \ParsedownExtra();

		$doc_content = $pd->text($doc->content);

		return view('documents.show', compact('doc', 'doc_content'));
	}
}

resources/views/admin/document/edit.blade.php
@extends('layouts.admin')

@section('title', 'Update Document')

@section('content')

<div class="panel panel-default">
	<div class="panel-heading">
		<h4>Update Document - {{$doc->name}}</h4>
	</div>
	<div class="panel-body">
		<form class="form-horizontal" action="{{ url('admin/documents/edit', $doc->id) }}" method="POST">
			{{ csrf_field() }}
			@if ($errors->all())
            	<div class="alert alert-danger" role="alert"><span class="glyphicon glyphicon-exclamation-sign"></span> {{ $errors->first() }}</div>
            @endif
            @if(Session::has('success'))
            	<div class="alert alert-success"><span class="glyphicon glyphicon-ok"></span> {{ Session::get('success') }}</div>
			@endif
			<div class="col-sm-12">
				<div class="form-group">
					<label for="name" class="control-label">Name</label>
					<input type="text" name="name" id="name" placeholder="Title" value="{{$doc->name}}" class="form-control">
				</div>
				<div class="form-group">
					<label for="description" class="control-label">Description</label>
					<textarea name="description" class="form-control" rows="2">{{$doc->description}}</textarea>
				</div>
				<div class="form-group">
					<label for="content" class="control-label">Content (Markdown)</label>
					<textarea name="content" class="form-control" rows="50">{{$doc->content}}</textarea>
				</div>
				<div class="form-group">
					<button class="btn btn-primary" type="submit">Submit</button>
				</div>
			</div>
		</form>
	</div>
</div>



@stop

resources/views/admin/document/index.blade.php
@extends('layouts.admin')

@section('title', 'Manage Documents')

@section('content')

<script src="{{ URL::asset('js/ui.js') }}"></script>
<script src="{{ URL::asset('js/touch.js') }}"></script>

<style>

    a.cursor:hover {
        cursor: pointer;
    }
    
</style>

<!-- Verify Delete Modal -->
<div id="verifyDelete" class="modal fade">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Confirm Deletion</h4>
      </div>
      <div class="modal-body">
      	<div>
      		Are you sure you wish to delete this document?<br />
            <br />
            This action is NOT reversable.<br /><br />
            <form action="{{ URL::to('/admin/documents/delete') }}" method='POST'>
                {{ csrf_field() }}
                <input type="hidden" id="documentidDelete" name='fileid' value='' />
                <button type="submit" class="btn btn-danger">I understand, delete this document</button>
            </form>
      	</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close without deleting</button>
      </div>
    </div>

  </div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		<h4>Manage Documents</h4>
	</div>
	<div class="panel-body">
			@if ($errors->all())
            	<div class="alert alert-danger"><span class="glyphicon glyphicon-exclamation-sign"></span> {{ $errors->first() }}</div>
            @endif
            @if(Session::has('success'))
            	<div class="alert alert-success"><span class="glyphicon glyphicon-ok"></span> {{ Session::get('success') }}</div>
			@endif
		<div class="row">
			<div class="col-md-6">
				<h5>Create Document</h5>
				<div class="col-xs-12">
					<form class="form-horizontal" action="{{ URL::to('/admin/documents') }}" method='POST'>
						{{ csrf_field() }}
						<div class="form-group">
							<label for="name" class="control-label">Document Name</label>
							<input value="{{ old('name') }}" type="text" name="name" id="name" class="form-control">
						</div>
                        <div class="form-group">
							<label for="description" class="control-label">Document Description</label>
                            <textarea name="description" id="description" class="form-control">{{ old('description') }}</textarea>
						</div>
						<div class="form-group">
							<label for="category" class="control-label">Category</label>
							<select name="category" class="form-control">
                                <option disabled selected>Please Select...</option>
                                @foreach($categories as $item)
								    <option value="{{$item->id}}">{{ $item->name }}</option>
                                @endforeach
							</select>
						</div>
                        <div class="form-group">
							<label for="content" class="control-label">Document Content (Markdown)</label>
                            <textarea name="content" id="content" class="form-control">{{ old('content') }}</textarea>
  				        </div>
						<div class="form-group">
							<button type="submit" class="btn btn-primary">Submit</button>
						</div>
					</form>
				</div>
			</div>
			<div class="col-sm-5 col-sm-offset-1">
				<blockquote>
					<p>Any document added will be inserted at the top of the sort order. You can reorder the documents by clicking the reorder icon and then dragging them to the order you desire. If you wish to change the category that a document is under, click the edit icon.</p>
                    <p>No HTML is allowed in the document description. Line breaks will be preserved.</p>
					<p>The content of the file is written in Markdown.</p>
				</blockquote>
			</div>
		</div>
		<h5 style="padding-bottom: 2px;">Modify Documents</h5>
		@foreach($categories as $cat)
			@if($cat->document_count)
				<div class="row">
					<div class="col-md-12">
						<h6 style="border-bottom: 1px solid #ddd; padding-bottom: 3px;">{{ $cat->name }}
							<a class="nohover pull-right cursor" title="Enable/Disable Sort Mode" id="sort_toggle_{{ $cat->id }}" onclick="sortButton({{ $cat->id }})">
								<span id="icon_sort_{{ $cat->id }}" style="color: #000;" class="glyphicon glyphicon-th-list"></span>
							</a>
						</h6>
						<ul class="list-group" id="ul_sort_{{$cat->id}}">
							@foreach ($cat->document as $document)
								<li id="sort_{{ $document->id }}" class="list-group-item">
									{{ $document->name }}
									<a class="pull-right nohover cursor" title="Delete this document" data-fileid='{{$document->id}}' data-toggle='modal' data-target='#verifyDelete' id='modalButton'>
									<span style="color: #871600; padding: 0 4px;" class="glyphicon glyphicon-trash"></span>
									</a>
									<a class="pull-right nohover" title="Edit this document" href="{{ url('admin/documents/edit', $document->uri_slug) }}">
									<span style="color: #002e7a; padding: 0 4px;" class="glyphicon glyphicon-pencil"></span>
									</a>
								</li>
							@endforeach
						</ul><button id="sort_save_{{$cat->id}}" onclick="saveList({{ $cat->id }})" class="btn btn-default">Save {{ $cat->name }}</button>
					</div>
				</div>
			@endif
        @endforeach
	</div>
</div>

<script>
    //Modals
    $('#modalButton').click( function (e) {
	   e.preventDefault();
    });
    $("a[data-toggle=modal]").click(function() 
    {   
        var fileid = $(this).data('fileid');
        $('#documentidDelete').val(fileid);
        
    });
	//Helper functions to allow queuing of class stuffs
	$.fn.queueAddClass = function(className) {
	    this.queue('fx', function(next) {
	        $(this).addClass(className);
	        next();
	    });
	    return this;
	};
	$.fn.queueRemoveClass = function(className) {
	    this.queue('fx', function(next) {
	        $(this).removeClass(className);
	        next();
	    });
	    return this;
	};
	$.fn.queueHtml = function(className) {
	    this.queue('fx', function(next) {
	        $(this).html(className);
	        next();
	    });
	    return this;
	};
	//OnLoad, make all 3 sortable lists sortable elements, then disable sorting.
	$( function() {
		$( "[id^=ul_sort]" ).sortable();
		$( "[id^=ul_sort]" ).sortable("disable");
	});
	//Toggle the sortability
	function sortToggle(iconid, listid) {
		if($(listid).sortable("option", "disabled")) {
			//sorting is disabled, enable it
			$(listid).sortable("enable");
			//Change the icon to green
			$(iconid).css('color', 'green');
			//Change the list items to green
			$(listid + '> .list-group-item').addClass('list-group-item-success');
			//Hide any links (edit/delete)
			$(listid + '> .list-group-item > a').hide();
		}
		else {
			//sorting is enabled, disable it
			$(listid).sortable("disable");
            //Change icon to black
			$(iconid).css('color', 'black');
            //Change list items back to white
			$(listid + '> .list-group-item').removeClass('list-group-item-success');
            //Show any hidden links
			$(listid + '> .list-group-item > a').show();
		}
		return false;
	};
	//Update the sort order in the DB
	function updateSort(listid, iconid, buttonid, cattext) {
		$(buttonid).addClass('btn-primary').html('Saving...');
		var url = "<?php echo url('/admin/document/sort'); ?>";
		//get new sort order into array
		var sorted = $(listid).sortable("toArray");
		//AJAX call to method to update sort order in DB
		$.ajax({
    		type: 'POST',
	        url: url,
    		data: {sort : sorted},
    		//if successfull
    		success: function() {
    			//disable sorting, update save button to show success, then wait 2 sec and reset save button back to page load status
				$(listid).sortable("disable");
				$(iconid).css('color', 'black');
				$(listid + '> .list-group-item').removeClass('list-group-item-success');
				$(listid + '> .list-group-item > a').show();
				$(buttonid).html('Saved!').delay(2000).queueRemoveClass('btn-primary').queueHtml(cattext);
    		}    
		});
	}
    
    function sortButton(catid) {
		sortToggle('#icon_sort_'+catid, '#ul_sort_'+catid);
        return false;
    }
    
    function saveList(catid) {
        updateSort('#ul_sort_'+catid, '#icon_sort_'+catid, '#sort_save_'+catid, $('#sort_save_'+catid).html());
        return false;
    }
</script>

@stop